### ISSUE TITLE
Use of reserved names

### ISSUE THREAD

**Issue by jwakely** [anadon/Sort-Comparisons-and-Performance-metrics#1]
Names like `_Distance` and `counter__assignments` are [reserved names](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier) so it is undefined for you to use them in your own code.

**Comment by anadon** [comment]
I'll change that today, but I don't that that is the core issue.

**Comment by jwakely** [comment]
> I'll change that today, but I don't that that is the core issue.

It's got nothing to do with your GCC bug report at all, it's a completely unrelated issue, which is why I filed it here.
